### ISSUE TITLE
Help with requesting data in API

### ISSUE THREAD

**Issue by Aadi-27** [tanaypratap/teamtanay.jobchallenge.dev#216]
I am finding it difficult to convert the response I am getting with my mapQuest API into JSON so that I could store, return the data as per needed. I have constructed a base URL and just have trouble with requesting data from the api in the fetch function. Please help mentors.

**Comment by tanaypratap** [comment]
provide sample code. or a repro when asking for help. 
Did you check stackoverflow for this? Code issues should be taken up with the API/library owners. Mentors are here for general guidelines only.

**Comment by Aadi-27** [comment]
Yes sir, I did a research on stackoverflow and in the documentation. I was just stuck in the part to fetch data from the api, it is a general issue and here I am attaching a snap. If it doesn't seem legitimate then I would find another api or project.

![Capture](https://user-images.githubusercontent.com/52901335/76850210-ea025700-686c-11ea-9a5c-e6c2ed58e7b7.JPG)
