### ISSUE TITLE
Guidelines for start contributing to the project

### ISSUE THREAD

**Issue by vipinmankar** [tanaypratap/teamtanay.jobchallenge.dev#228]
I have recently joined the group as now i have got to know about this community, please guide from where i can get the project and how can i start development on it.
Thank you

**Comment by rahul1116** [comment]
Visit the [official website](https://2020.teamtanay.jobchallenge.dev) and go through the [FAQ's](https://2020.teamtanay.jobchallenge.dev/faqs) too while you're there.
