### ISSUE TITLE
[Idea] Making a Platform similar to Goodreads for Podcasts. 

### ISSUE THREAD

**Issue by Megha-Pathak** [tanaypratap/teamtanay.jobchallenge.dev#230]
I looking forward to make a social catalogue platform similar to goodreads for the podcasts where people can find relevant podcasts by reviews posted by the users. 
A review database for this can be build from scratch but are there any APIs, language or resources anyone can suggest for this idea?

**Comment by geekysrm** [comment]
Hi @Megha-Pathak , from a quick Google search I could find this https://www.listennotes.com/api/
Hope it helps

**Comment by tanaypratap** [comment]
I am hoping this is resolved and hence closing this issue.
