### ISSUE TITLE
[Help][Suggestion needed] Bootstrap in Gatsby/react

### ISSUE THREAD

**Issue by mihirgupta0900** [tanaypratap/teamtanay.jobchallenge.dev#237]
What is the best way to implement bootstrap in a react/Gatsby project? I'm having a bit of trouble with that. I found out a few ways but still want to know what's better.
1. Installing react bootstrap in the project and importing it. While this is working, I'm having to learn all the names of the navbar and forms again for the imported classes. One more issue is that I'm not finding a way  to overwrite the css implemented by bootstrap when using bootstrap components (such as text color in navbar)
2. Adding the link tah in the Helmet tag in a layout js file. This works fine for the css (which can be implemented with classNames) but when I put the script tag in Helmet, it's throwing error.

So what is a better way to use it and if any other way to implement it? Because adding custom css for each project is very time consuming. 
Thank you for the suggestions in advance.

**Comment by cdking007** [comment]
https://react-bootstrap.github.io/getting-started/introduction/

hope you get your ans by vising this link 😃

**Comment by mihirgupta0900** [comment]
Thanks @cdking007 , I looked into that earlier but looked into it once more.
Solved a few problems.
Any suggestions on how to override css provided by bootstrap?

**Comment by cdking007** [comment]
use !important flag in css after the value

**Comment by tanaypratap** [comment]
Do close the issue if the problem is resolved. It will be good for housekeeping..
