### ISSUE TITLE
[Ideas] [BlogPost] 19 App Ideas for the Job Challenge

### ISSUE THREAD

**Issue by swapnadeepmohapatra** [tanaypratap/teamtanay.jobchallenge.dev#247]
## This is a blog with all the ideas that Tanay and Sarosh discussed on the Instagram Live.

https://medium.com/@swapnadeep456/19-app-ideas-for-the-job-challenge-5aa0c4af51d1?sk=6074a5192643587cc6ecd75dae134e51

Reviews and suggestions are most welcome. 

And please do share the blog. I have kept the whole thing discussed during Instagram live in a nutshell.

**Comment by tanaypratap** [comment]
This is good.
Please mention the context. Where and how you have these ideas. Otherwise it looks like you have come with all of this which feels like plagiarism.
Also, put a PR in this repository inside blog section.

**Comment by swapnadeepmohapatra** [comment]
I have made the changes. You can view it here: https://medium.com/@swapnadeep456/19-app-ideas-for-the-job-challenge-5aa0c4af51d1
