### ISSUE TITLE
[Project][Issue] Unknown arrow buttons appearing out of nowhere

### ISSUE THREAD

**Issue by mritunjaysaha** [tanaypratap/teamtanay.jobchallenge.dev#265]
I've been facing some problem in this. 
Some unknown elements occurred from somewhere online on the desktop site.
site link: covidupdate.netlify.com
github link: https://github.com/mritunjaysaha/corona

The data is also not loading.

Thanks.

**Comment by 4nmolChaudhary** [comment]
A scroll bar is appearing into your <h4> element,
so add this CSS to your <h4> element;
h4{
font-size:1.5rem; /* you have this already */
overflow:hidden;
}

By specifying overflow property to hidden, your problem will be solved.
Do this, if it is solved do response.😅😅😅😅😅😅

**Comment by mritunjaysaha** [comment]
Thanks. 
It worked
