### ISSUE TITLE
How to start after pull request is merged ?

### ISSUE THREAD

**Issue by aadhar54** [tanaypratap/teamtanay.jobchallenge.dev#281]
**Hello Tanay ,**

Hope the community and you are fine .My pull request has been merged and I am registered as a participant in the challenege .
How to start now ?

**I know you are doing so much but from here , its looking abstract .**

##What's next and what to make ?

**Comment by gkanishk** [comment]
Hey @aadhar54 ,
Hope you are doing well good to see you participating in the challenge.
For complete details about the challenge and how and what to make kindly visit [jobchallenge.dev](https://jobchallenge.dev)
