### ISSUE TITLE
Unable to run create-react-app

### ISSUE THREAD

**Issue by jusergit30** [tanaypratap/teamtanay.jobchallenge.dev#288]
I have installed vs code and node JS on my laptop but I do not have internet connectivity. I am trying to run the npm create-react-app command but it gives error. The error is:
npm ERR! code ENOTFOUND
npm ERR! errcode ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/create-react-app failed,
reason: getaddrinfo ENOTFOUND registry.npmjs.org

I tried google but didnt found a solution that works.  How can i run the npm commands like create react app and get react app running offline without internet connection. 
![Uploading IMG_20200326_133144-01.jpeg…]()

**Comment by 4nmolChaudhary** [comment]
**create-react-app** is a cli based tool to create a React Application which required to install first in your system before using it, which require a **internet connection**.

you can also use a package runner tool for npm v5.2+
`npx create-react-app my-app`
use above command to create a react app

**Comment by cdking007** [comment]
hey create-react-app must be installed first globally on your laptop and for that you need internet connection and if you dont want to install it globally use npx create-react-app appname hope u got it.

**Comment by jusergit30** [comment]
Thanks for the info
