### ISSUE TITLE
[Project][Feedback][Improvements]Review required for my first project

### ISSUE THREAD

**Issue by Lakshay-Batra** [tanaypratap/teamtanay.jobchallenge.dev#309]
#Utility and Fun app#
Made a web app with many small features to solve some daily problems
It has
Utility section.
1. BMI calculator
2. Personal Expense calculation
3. Toss game
4. Who will pay the bill at restaurant.
Fun section.
1. Drum set
2. Love calculator
3. Simon game
Below is the link👇
[Click here]( https://utilitywithfun.netlify.com)

[Git hub repo](https://github.com/Lakshay-Batra/Project1.Utility.Fun)

I've used
HTML, CSS, Vanila js, Bootstrap, jQuery

**Comment by itaditya** [comment]
I can't believe this is your project. Super awesome!

Feedback-

You can use css flexbox to keep the footer at the bottom 
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/15871340/78891410-24829c80-7a85-11ea-9573-11b5ee1487fd.png">

Read this for help https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/

**Comment by Lakshay-Batra** [comment]
Thank you , will surely look after your suggestion. @itaditya

**Comment by Lakshay-Batra** [comment]
I have made changes(footer in the bottom) to the project as you said and your resource really helped, @itaditya
