### ISSUE TITLE
[Project][Feedback] MERN stack chat app

### ISSUE THREAD

**Issue by JatinRanka** [tanaypratap/teamtanay.jobchallenge.dev#336]
First of all, great thanks to you guys for doing this job challenge.

I just created a MERN stack chat app using socket.io for real-time connection. Here is the link to the project:
https://chat-app-jatin.netlify.com/

How to use:
1. Open app
2. Enter name and room.
3. Chat with all the users who joined in that room.

Here is the link to GitHub repo:
https://github.com/JatinRanka/Chat-App

I am facing an issue here. I have initialized git in 2 folders: client & server and hosted both in different places. Netlify for client and Heroku for the server.
How can I upload the code in GitHub such that it is available in a single repo? 

Once again, thank you so much for doing all this. You guys are doing a tremendous job. Let me know if you need any help from me. I would love to help you.

**Comment by anurag-majumdar** [comment]
Hi @JatinRanka, try initializing git repo on the parent folder with your app name and keep client and server folders inside that parent folder.
Also, make sure the git repo is not initialized inside client and server folders.

Regarding the project for chat room.
We saw that exactly the same UI with it's features are being used as per the following project:

Video: https://www.youtube.com/watch?v=ZwFA3YMfkoc&t=4984s
GitHub: https://github.com/adrianhajdin/project_chat_application

We would suggest you to come back with your own project with use cases.

Here at Job Challenge, we are very strict regarding the originality of a project as it comes from the students. It need not matter that the project be perfect. We appreciate each and every student for the hard work they put in.

Please open a new GitHub issue with a new project once you are ready.
