### ISSUE TITLE
[Projects] Feedback on my projects

### ISSUE THREAD

**Issue by Bhupesh-V** [tanaypratap/teamtanay.jobchallenge.dev#342]
### Projects
- [defe(devfeed) - Tech Feed Aggregator for Developers & Tech Enthusiasts](https://github.com/Bhupesh-V/defe)
- [Memer Action - A GitHub Action for Programmer Memes](https://github.com/Bhupesh-V/memer-action)

**Comment by gkanishk** [comment]
hey @Bhupesh-V please create multiple issues for projects and blogs not all inside single issue

**Comment by Bhupesh-V** [comment]
> hey @Bhupesh-V please create multiple issues for projects and blogs not all inside single issue

Sure

**Comment by gkanishk** [comment]
separate issues for individual ones same goes for blogs
