### ISSUE TITLE
[Blog][Feedback] THE FRONT-END I KNOW

### ISSUE THREAD

**Issue by Uyadav207** [tanaypratap/teamtanay.jobchallenge.dev#344]
Hey there,
Done with my First Blog and requires feedback from mentors , Kindly Help me Improve .
thanking You,
@Uyadav207 

# THE FRONT-END I KNOW
* Visit the Link [**THE FRONT-END I KNOW**](https://link.medium.com/l21IFN9rE5)
* Provided the reader with the Links and path to learn Front-end.

**Comment by tanaypratap** [comment]
Publish the blogs to dev.to. people will comment. That's the best feedback.

Let's reserve mentors for project and portfolio feedbacks.

./Tanay
I teach coding for free online. If you or someone you know is looking out
to learn join 30K students across 50 countries to learn web development
with me on learncodingfree.org

**Comment by Uyadav207** [comment]
Roger That 🖖,
@tanaypratap
