### ISSUE TITLE
Permission for using Job Challenge official icon in my project

### ISSUE THREAD

**Issue by JowelTisso** [tanaypratap/teamtanay.jobchallenge.dev#351]
@tanaypratap sir, I wanted to use your job challenge icon in my project.

![icon](https://user-images.githubusercontent.com/52632590/79239503-44073400-7e8e-11ea-8d91-bfdcbadbc356.jpg)
Particularly this one.

I have made an app as my first project and wanted to use your icon as my app icon, as participants would be familiar with it.

My app is basically a participants details viewing app( project related details ).
Students can check the total number of participants in the project, view their profile picture as of twitter and their field of interest. and also can sort them out with respective skills. It also has a feature of checking overall project timeline and creating a new project to keep track of each project, and much more. 

So, this app is fully related to the job challenge journey which would be helpful for the participants.
So, as of that was thinking of using your icon in my App cause it looks good and fits my apps purpose.
With regards,

**Comment by tanaypratap** [comment]
I think that's a great idea. Use it but modify the icon with an
'unofficial' banner somewhere. As this is not an official app and I don't
want to confuse people with this.

./Tanay
I teach coding for free online. If you or someone you know is looking out
to learn join 30K students across 50 countries to learn web development
with me on learncodingfree.org

**Comment by JowelTisso** [comment]
Ok , will follow your guideline.
Thank you sir.
