### ISSUE TITLE
[Bug][React][Gatsby] Use a variable which is defined in componentDidMount() in server side rendering

### ISSUE THREAD

**Issue by mihirgupta0900** [tanaypratap/teamtanay.jobchallenge.dev#370]
Hello mentors, 
I'm making a website to with Gatsby and need to conditionally render a React component, for which I need to use the window object (window.innerWidth), but using that throws an error during the server side rendering. Then I put the window object in the componentDidMount(), but I need to use a boolean variable from there. So how do I do that?  
The problem is in the index.js inside src/pages in the github repo below.

[Github repo](https://github.com/mihirgupta0900/personal-website)

**Comment by itaditya** [comment]
This is a common problem with Server Side Rendering. You have to use a state variable and then update its value in componentDidMount;

```js
state = {
  show: false,
};

componentDidMount() {
  // inside your conditions.
  this.setState({
    show: true,
  });
}

render() {
  return (
    <div>
     {this.state.show ? 'Show' : 'Hide' }
    </div>
  );
}
```

**Comment by mihirgupta0900** [comment]
Thanks! Understood it.
