### ISSUE TITLE
[Project][Feedback] e-Commerce App 

### ISSUE THREAD

**Issue by swapnadeepmohapatra** [tanaypratap/teamtanay.jobchallenge.dev#401]
Hey Guys,

I hope you all are doing fine and staying safe inside your home. I have made this full-stack E-Commerce App with MERN stack. Kindly provide your reviews on this app. 

Link of the app -> https://ecom.swapnadeep.com/  or  https://swapnadeep-ecom.netlify.app/cart 

And thank you in advance for helping us out.

**Comment by tanaypratap** [comment]
Fix the Mobile view. That's important. Design looks cool.  But you're using too many colors. Understand that it's not a candy store.

**Comment by swapnadeepmohapatra** [comment]
I have changed the color theme and used the grey color for all the cards bg and violet color for all the buttons. I have also written media query to make it mobile compatible. Please check the updated site. 
 
## https://ecom.swapnadeep.com/ or https://swapnadeep-ecom.netlify.app/
