### ISSUE TITLE
slug error for the participant Diresh kumar pradhan in the participants list

### ISSUE THREAD

**Issue by JowelTisso** [tanaypratap/teamtanay.jobchallenge.dev#424]
Hello maintainers,
I see there is a slug address problem for one of the participants named Diresh Kumar Pradhan.
When link is clicked it leads to the home page of the job challenge when it should lead to his profile.
I found this issue and thought to report it  which will also help me fetch data for my app.
So, hope you can look into it and resolve it.
Thank you.

**Comment by gkanishk** [comment]
thanks for raising the issue!
