### ISSUE TITLE
[Project][Feedback] AnimeBuzz - To get details about anime shows and new seasons.

### ISSUE THREAD

**Issue by mallikarjun2000** [tanaypratap/teamtanay.jobchallenge.dev#434]
Hello Mentors , 

This is my first project made using only React Js .

# Anime Buzz
Anime buzz is a website to know details about your favorite anime .In this website you can know about :

        * Latest Upcoming anime List.
        * Search About your favorite anime.
        * Watch Latest Trailers.
        * Get List of Top Anime genre wise.
   
 [click here](http://animebuzz.herokuapp.com) to visit the website.

GitHub [link](https://github.com/mallikarjun2000/animewebsite)

I hope you like it and please give any suggestions to improve the design.

**Comment by DevKing9904** [comment]
Nice project Mallikarjaun.
