### ISSUE TITLE
[Project][Feedback] Relaxify--My own React Spotify Player...

### ISSUE THREAD

**Issue by Uyadav207** [tanaypratap/teamtanay.jobchallenge.dev#435]
### How to use
* Go on to [Relaxify-Link](https://relaxify.netlify.app/)
* Click on [***Login to the Spotify*** ] button.
* Enter your spotify account details i.e email | password .etc
* Now open your Phone or any device in which spotify has been installed.
* Now play a song on ***your Device***  with spotify application.
* Now Click on ***Now PLaying*** button on my Website.
* And you now be able to see List of devices in your phone . SELECT **RELAXIFY-BY UTKARSH**
* And again click on the now playing button and control the application with my website .
* what's the fun part is ... You don't need spotify for changing tracks...You can do that with my website now.
* Now close your spotify application from phone and listen it in RELAXIFY-by UTKARSH 😎😜👈❤

## Consideration
* Mentors Kindly Reply and Give reviews
  * Specially @tanaypratap  sir And @gkanishk .
* IF not able to Run the product..
* Whatsapp Number : 7906498071
* Email : yadavutkarsh207@gmail.com
* Please Review it ...
Thanking u All, ❤
@Uyadav207

**Comment by gkanishk** [comment]
That's awesome and thanks for mentioning me 😃 
Few points:
- After changing the track Now Playing section should change
![image](https://user-images.githubusercontent.com/33570551/80275106-d3b5a980-86fc-11ea-973b-c1cbca38024d.png)
- Is it possible to change the device from here I tried to change but it didn't
![image](https://user-images.githubusercontent.com/33570551/80275170-1ecfbc80-86fd-11ea-88ce-99eca3d81d27.png)
- Also if we select different device from the list and change track it doesn't work.
Nice concept Kudos!!! 👏👏
Rest over to you @tanaypratap 😃

**Comment by Uyadav207** [comment]
Thanks @gkanishk , ❤👍
for the review and ya..

* You cannot change the Device from my website... Instead you can change it from your spotify Official application.
* I will remove the Icon ASAP.
* The **Check Now Playing** Button does two Things 
  * Refresh the token.
  * Change the Thumbnail.
* For seeing the New Thumbnail and refreshing the token You have to Click now Playing...After every one Hour..
* That's the Private Policy of the Spotify that the token can only last upto 1 Hour...
* and after clicking now playing I am allowing the user to refresh the token..
* THE ONLY THING I CAN DO IS REMOVE THE CONNECTOR ICON AND TRY TO ADD SOMETHING NEW

Thank u,
@Uyadav207

**Comment by Uyadav207** [comment]
@gkanishk ,
* After loading the site the Spotify refreshes the token.
* But u need not login again and again .
* Click on the Check now playing button ...
* You will again see my name in your original Spotify application's available devices...click and play again .
 😁❤ ,
thanks....
@Uyadav207
