### ISSUE TITLE
Very old dates are getting displayed in two of the pages

### ISSUE THREAD

**Issue by anubhav8421** [tanaypratap/teamtanay.jobchallenge.dev#489]
![image](https://user-images.githubusercontent.com/18699797/80966929-1ed56800-8e33-11ea-998f-16ff3cc0176a.png)
![image](https://user-images.githubusercontent.com/18699797/80966958-30b70b00-8e33-11ea-81ce-288ec3b87b1e.png)
 As one can see in the above images, the date mentioned is very old and does not look good. 
Also, these pages are not something on which date should be displayed. In my opinion, the dates should be removed. What

**Comment by gkanishk** [comment]
Thanks for raising the issue.
