### ISSUE TITLE
[Issue] [MERN] [OAuth] [Backend] Implement OAuth in MERN stack

### ISSUE THREAD

**Issue by mihirgupta0900** [tanaypratap/teamtanay.jobchallenge.dev#573]
Hello Mentors! 
I had been working on a project to in the MERN stack and wanted to implement OAuth with Google, Facebook etc, but I am having issues finding the best way to implement it. I found a few ways but they don't seem to work for me.
1. Using PassportJs. This is a wonderful library but I am having issues with redirecting to the client-side (React) after authentication.
2. Using firebase. This method would be very easy but firebase seems to store the users in their database, I may not be 100% correct, please correct me. 
So mentors, what is the best way of implementing OAuth in a MERN project? 

Links of Github repos would be very appreciated and would help me to learn more about it.

Thanks in advance!

**Comment by tanaypratap** [comment]
Use firebase for now. Yes the users are in firebase database but that shouldn't be a blocker for a side project. 
Ship first, scale second.
