### ISSUE TITLE
[Project-1][Review]Coffee House

### ISSUE THREAD

**Issue by Kalyan-1707** [tanaypratap/teamtanay.jobchallenge.dev#585]
Dear mentors just completed my first project.Have a look and leave valuable feedback.

**Coffee House**
  https://thunder1707.000webhostapp.com/
Github repo - https://github.com/Kalyan-1707/coffee 

Major features
* Customers can order without **_creating account_**.
* Customers can  make **_Payment_** online dc/cc/net banking...
* Customers are notified through **_sms_**.
* Owners use **_admin_** panel to montior the orders based on token number..

For testing  use

Debit card

  4242 4242 4242 4242
  
   MM/YY -  02/23   CVV - 123

To access **admin panel**

* click on coffee(title) in navbar on index page(https://thunder1707.000webhostapp.com/).
* username - admin.
* password - admin.

**Comment by BaseMax** [comment]
Hello Dear,
I'm not a mentor, And I don't know if I'm allowed to send a message here.

Please read my message as a friend who want to coding and write bugs :-D

### I see some good features:
- Modal
- CSS Animations
- PHP files
- JS Skills

### Also some problems:
- You need to increase width of table in "Check out" modal.
- UI is not suitable, this means you are not a designer, But i suggest you to see some concept and design before starting coding.
- Press "Enter" key in the form not submit form.
- You did not comply structure of HTML (There is <script> tag after </html>)
- Syntax is not clean
- Some extra tag are closed!
![code](https://user-images.githubusercontent.com/2658040/81728172-482f6d00-949f-11ea-835d-f7c3e1413b85.jpg)

You can improve and solve that, it's not end of the world :-D

It's your first project? I like it.
Continue, you are awesome.

Sorry for message, I want to see more work from you.

Regards,
Max Base,

**Comment by Kalyan-1707** [comment]
> Hello Dear,
> I'm not a mentor, And I don't know if I'm allowed to send a message here.
> 
> Please read my message as a friend who want to coding and write bugs :-D
> 
> ### I see some good features:
> * Modal
> * CSS Animations
> * PHP files
> * JS Skills
> 
> ### Also some problems:
> * You need to increase width of table in "Check out" modal.
> * UI is not suitable, this means you are not a designer, But i suggest you to see some concept and design before starting coding.
> * Press "Enter" key in the form not submit form.
> * You did not comply structure of HTML (There is <script> tag after )
> * Syntax is not clean
> * Some extra tag are closed!
>   ![code](https://user-images.githubusercontent.com/2658040/81728172-482f6d00-949f-11ea-835d-f7c3e1413b85.jpg)
> 
> You can improve and solve that, it's not end of the world :-D
> 
> It's your first project? I like it.
> Continue, you are awesome.
> 
> Sorry for message, I want to see more work from you.
> 
> Regards,
> Max Base,

Thanks for feedback.
I will improve it.

**Comment by Kalyan-1707** [comment]
> Hello Dear,
> I'm not a mentor, And I don't know if I'm allowed to send a message here.
> 
> Please read my message as a friend who want to coding and write bugs :-D
> 
> ### I see some good features:
> * Modal
> * CSS Animations
> * PHP files
> * JS Skills
> 
> ### Also some problems:
> * You need to increase width of table in "Check out" modal.
> * UI is not suitable, this means you are not a designer, But i suggest you to see some concept and design before starting coding.
> * Press "Enter" key in the form not submit form.
> * You did not comply structure of HTML (There is <script> tag after )
> * Syntax is not clean
> * Some extra tag are closed!
>   ![code](https://user-images.githubusercontent.com/2658040/81728172-482f6d00-949f-11ea-835d-f7c3e1413b85.jpg)
> 
> You can improve and solve that, it's not end of the world :-D
> 
> It's your first project? I like it.
> Continue, you are awesome.
> 
> Sorry for message, I want to see more work from you.
> 
> Regards,
> Max Base,



> Hello Dear,
> I'm not a mentor, And I don't know if I'm allowed to send a message here.
> 
> Please read my message as a friend who want to coding and write bugs :-D
> 
> ### I see some good features:
> * Modal
> * CSS Animations
> * PHP files
> * JS Skills
> 
> ### Also some problems:
> * You need to increase width of table in "Check out" modal.
> * UI is not suitable, this means you are not a designer, But i suggest you to see some concept and design before starting coding.
> * Press "Enter" key in the form not submit form.
> * You did not comply structure of HTML (There is <script> tag after )
> * Syntax is not clean
> * Some extra tag are closed!
>   ![code](https://user-images.githubusercontent.com/2658040/81728172-482f6d00-949f-11ea-835d-f7c3e1413b85.jpg)
> 
> You can improve and solve that, it's not end of the world :-D
> 
> It's your first project? I like it.
> Continue, you are awesome.
> 
> Sorry for message, I want to see more work from you.
> 
> Regards,
> Max Base,

I had fixed the problems .
Have a look at it .

**Comment by BaseMax** [comment]
> I had fixed the problems .
> Have a look at it.

Great, Use a pretty HTML online service or beautifuller tool.

### What's `</br>` ?

https://stackoverflow.com/questions/1726073/is-it-sometimes-bad-to-use-br
- In HTML (up to HTML 4): use `<br>`
- In HTML 5: `<br>` is preferred, but `<br/>` and `<br />` is also acceptable
- In XHTML: `<br />` is preferred. Can also use `<br/>` or `<br></br>`

---------

### orders.php problem

https://thunder1707.000webhostapp.com/orders.php

```
<br />
<b>Notice</b>:  Undefined index: customer_num in <b>/storage/ssd1/140/13403140/public_html/orders.php</b> on line <b>12</b><br />
<br />
<b>Notice</b>:  Undefined index: customer_name in <b>/storage/ssd1/140/13403140/public_html/orders.php</b> on line <b>14</b><br />
<br />
<b>Notice</b>:  Undefined index: items in <b>/storage/ssd1/140/13403140/public_html/orders.php</b> on line <b>15</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /storage/ssd1/140/13403140/public_html/orders.php:12) in <b>/storage/ssd1/140/13403140/public_html/orders.php</b> on line <b>21</b><br />
```

Try:
```php
<?php
if(!isset($_POST["customer_num"])) {
   exit("Error!");
}
?>
PAGE HTML CODE
```


Not HTML5?

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
```

Thanks for you trying...
You are great, I follow you.

Regards,
Max Base

**Comment by Kalyan-1707** [comment]
> Great, Use a pretty HTML online service or beautifuller tool.
> Try:
> 
> ```
> <?php
> if(!isset($_POST["customer_num"])) {
>    exit("Error!");
> }
> ?>
> PAGE HTML CODE
> ```

> Regards,
> Max Base

 Added the php code 
Modified ```</br>``` to  ```<br>```
Added <!DOCTYPE....
Thanks for your time and feedback.
