### ISSUE TITLE
Updating Hiring Partners section

### ISSUE THREAD

**Issue by sandeep-devarapalli** [tanaypratap/teamtanay.jobchallenge.dev#592]
To coordinate effectively with hiring partners, we have created a group on WhatsApp: #hiringHub #jobChallenge, link: http://shorturl.at/buIOP

Please include the name of the group, and the group invite along with the description under _"want to be a hiring partner?"_

Also, kindly introduce Hackstrap as a coordinator for the hiring partners. The wordings can be as follows.

Hackstrap (hackstrap.com) is part of the jobChallenge team as the coordinator for the hiring partners and will be available to answer any questions hiring partners have and to give them the necessary clarifications.

**Comment by gkanishk** [comment]
Sure will add the details!!

**Comment by gkanishk** [comment]
Hey @sandeep-devarapalli ,
I have updated the required details please have a look if this looks good to merge.
![image](https://user-images.githubusercontent.com/33570551/81823441-f4319080-9551-11ea-86af-1a159a21e8df.png)
