### ISSUE TITLE
[Need help] [React Native] How to access, update and save array index in React Native?

### ISSUE THREAD

**Issue by cmcodes1** [tanaypratap/teamtanay.jobchallenge.dev#622]
https://stackoverflow.com/questions/61805943/how-to-access-update-and-save-array-index-in-react-native

**Comment by 4nmolChaudhary** [comment]
Explain your in detail bro that what expected output you want show its sample also, I am still not able to understand what do you need exactly ( Ex. you are using array and want to increment the count?? )

Put the problem with proper explanation again, I will see to it

**Comment by cmcodes1** [comment]
I am using two arrays **present_count** and **total_count**.
present_count[0] will store the present count (how many times blue button is clicked) for the first subject, present_count[1] will store for the next subject and so on).
Array total_count will do the same thing, but will get updated for both the buttons (red or blue).
present_count[i] will appear on LHS of slash sign and total_count[i] will appear on the RHS of slash sign.

**Comment by cmcodes1** [comment]
@4nmolChaudhary 
I have updated the description in simple words.
