### ISSUE TITLE
[Project][Feedback] Crwn Clothing - A React/Redux Fashion E-commerce Website

### ISSUE THREAD

**Issue by Shivraj97** [tanaypratap/teamtanay.jobchallenge.dev#672]
Hello maintainers.
Please have a look at my new project and kindly give your feedback.

Crwn Clothing - A React/Redux Fashion E-commerce Website

It is a fashion e-commerce store. The user can shop for fashionable clothes and add them to cart and can checkout using Stripe. I have added Firebase authentication for SignIn and also added SignIn/SignUp option using custom email/password. I have used Redux for state management.

Live Demo - [https://crwn-fashionstore-live.herokuapp.com](https://crwn-fashionstore-live.herokuapp.com)

**Comment by KousikTheHunk** [comment]
Andre negoi course !!! =D Good one ...

**Comment by Uyadav207** [comment]
Hey @Shivraj97, 👋
Nice...❤work..
## Some Suggestions :  

* Alert message is must. As I picked a Denim shirt and clicked 10 times and saw No change no popups..and when i opened my cart I found 10 shirts being added.

* Have a look to responsive view..

![Annotation 2020-05-24 000910](https://user-images.githubusercontent.com/50916299/82738240-cb7c7880-9d53-11ea-80f5-f31638fe3a30.png)

* It would be good if you can show **Username** instead the **Signed In**  or  **Signed Out**

Thanks..
Keep Going.. 👍
@Uyadav207

**Comment by Shivraj97** [comment]
I will make it responsive. And i will add alert message. Thanks for the suggestions

**Comment by Uyadav207** [comment]
Not a Mentor..
Just suggested some improvements..
👍🏻
