### ISSUE TITLE
[Blog-3] Node.js's core things

### ISSUE THREAD

**Issue by kaushalkoladiya** [tanaypratap/teamtanay.jobchallenge.dev#847]
I wrote Blog on the Node.js core things where you would know how to take input from the console like any other programming language.
[link](https://dev.to/kaushal/node-js-1odl)

**Comment by Shriram-Balaji** [comment]
@kaushalkoladiya  Good start with the blog. A couple of suggestions before finalizing a blog post:

* Make sure to avoid typos in the page, there are a few of them in the post.
* It'd be great to start of with an introduction, as to what the contents of the post are. Say for eg, when you mention that you are talking about node core, it'd be great to explain what parts of that you are going to talk about in this post.,
*  Also add links to the node documentation for modules that you have talked about.
*  Research more about a specific module, and add more details - currently the post has a one line description for each module. it'd be great to do something like:
   - Go in-depth into a specific module, see what are all real-time usecases to the functions in the module. 
   - Add a small blog post, for just that module.
   - Eventually, you will end up with a multi part blog post series, covering all of them in depth too.

Appreciate the efforts taken to create this blog post, expecting that you would write more in the future :)

**Comment by kaushalkoladiya** [comment]
> @kaushalkoladiya  Good start with the blog. A couple of suggestions before finalizing a blog post:
> 
> * Make sure to avoid typos in the page, there are a few of them in the post.
> * It'd be great to start of with an introduction, as to what the contents of the post are. Say for eg, when you mention that you are talking about node core, it'd be great to explain what parts of that you are going to talk about in this post.,
> *  Also add links to the node documentation for modules that you have talked about.
> *  Research more about a specific module, and add more details - currently the post has a one line description for each module. it'd be great to do something like:
>    - Go in-depth into a specific module, see what are all real-time usecases to the functions in the module. 
>    - Add a small blog post, for just that module.
>    - Eventually, you will end up with a multi part blog post series, covering all of them in depth too.
> 
> Appreciate the efforts taken to create this blog post, expecting that you would write more in the future :)


Thanks for reviewing my blog.
